spring.application.name=complaintsystem

spring.datasource.url=jdbc:mysql://localhost:3306/complaintdb
spring.datasource.username=root
spring.datasource.password=Pooji@31.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true